// Build-time codegen: reads config/customers/*.yaml and emits a typed TS
// module (src/lib/config/generated.ts) so the app can import customer
// config like any other TS module — no runtime YAML parsing needed.
//
// Run via `bun run scripts/generate-customer-config.ts` (wired into the
// `predev`/`prebuild` package.json scripts).

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CUSTOMERS_DIR = join(__dirname, "..", "config", "customers");
const OUT_FILE = join(__dirname, "..", "src", "lib", "config", "generated.ts");

const files = readdirSync(CUSTOMERS_DIR).filter((f) => f.endsWith(".yaml"));

if (files.length === 0) {
  throw new Error(`No customer YAML config files found in ${CUSTOMERS_DIR}`);
}

const entries = files.map((file) => {
  const customerId = file.replace(/\.yaml$/, "");
  const raw = readFileSync(join(CUSTOMERS_DIR, file), "utf-8");
  const parsed = parse(raw) as unknown;
  return { customerId, parsed };
});

const customerIds = entries.map((e) => e.customerId);

const banner = `// AUTO-GENERATED by scripts/generate-customer-config.ts — do not edit by hand.
// Source of truth: config/customers/*.yaml
`;

const body = `${banner}
export type CustomerId = ${customerIds.map((id) => JSON.stringify(id)).join(" | ")};

export type CustomerConfig = {
  brand: {
    name: string;
    logoInitials: string;
    tagline: string;
    productLine: string;
    description: string;
    footer: string;
  };
  theme: {
    primary: string;
    steel: string;
    copper: string;
    danger: string;
    ok: string;
  };
  nav: {
    overview: string;
    shipments: string;
    inventory: string;
    alerts: string;
    insights: string;
  };
  kpis: {
    production: { label: string; unit: string };
    refineryUtil: { label: string; unit: string };
    inventoryDays: { label: string; unit: string };
    priceBenchmark: { label: string; unit: string };
  };
  table: {
    shipments: {
      vessel: string;
      route: string;
      corridor: string;
      load: string;
      eta: string;
      status: string;
    };
    inventory: {
      tanksTracked: string;
      totalCapacity: string;
      avgFill: string;
      above90: string;
    };
  };
};

export const CUSTOMER_IDS: CustomerId[] = ${JSON.stringify(customerIds)};

export const CUSTOMER_CONFIGS: Record<CustomerId, CustomerConfig> = ${JSON.stringify(
  Object.fromEntries(entries.map((e) => [e.customerId, e.parsed])),
  null,
  2,
)};
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, body, "utf-8");
console.log(`Generated ${OUT_FILE} for customers: ${customerIds.join(", ")}`);
