/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as HseRouteImport } from './routes/hse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrdRouteImport } from './routes/prd'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as WellsRouteImport } from './routes/wells'
import { Route as PartnersPartnerIdRouteImport } from './routes/partners.$partnerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const HseRoute = HseRouteImport.update({
  id: '/hse',
  path: '/hse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdRoute = PrdRouteImport.update({
  id: '/prd',
  path: '/prd',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const WellsRoute = WellsRouteImport.update({
  id: '/wells',
  path: '/wells',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersPartnerIdRoute = PartnersPartnerIdRouteImport.update({
  id: '/partners/$partnerId',
  path: '/partners/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/forecasting': typeof ForecastingRoute
  '/hse': typeof HseRoute
  '/login': typeof LoginRoute
  '/prd': typeof PrdRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/roadmap': typeof RoadmapRoute
  '/tickets': typeof TicketsRoute
  '/wells': typeof WellsRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/forecasting': typeof ForecastingRoute
  '/hse': typeof HseRoute
  '/login': typeof LoginRoute
  '/prd': typeof PrdRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/roadmap': typeof RoadmapRoute
  '/tickets': typeof TicketsRoute
  '/wells': typeof WellsRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/forecasting': typeof ForecastingRoute
  '/hse': typeof HseRoute
  '/login': typeof LoginRoute
  '/prd': typeof PrdRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/roadmap': typeof RoadmapRoute
  '/tickets': typeof TicketsRoute
  '/wells': typeof WellsRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/forecasting'
    | '/hse'
    | '/login'
    | '/prd'
    | '/production'
    | '/products'
    | '/profile'
    | '/reconciliation'
    | '/roadmap'
    | '/tickets'
    | '/wells'
    | '/partners/$partnerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/forecasting'
    | '/hse'
    | '/login'
    | '/prd'
    | '/production'
    | '/products'
    | '/profile'
    | '/reconciliation'
    | '/roadmap'
    | '/tickets'
    | '/wells'
    | '/partners/$partnerId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/forecasting'
    | '/hse'
    | '/login'
    | '/prd'
    | '/production'
    | '/products'
    | '/profile'
    | '/reconciliation'
    | '/roadmap'
    | '/tickets'
    | '/wells'
    | '/partners/$partnerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ForecastingRoute: typeof ForecastingRoute
  HseRoute: typeof HseRoute
  LoginRoute: typeof LoginRoute
  PrdRoute: typeof PrdRoute
  ProductionRoute: typeof ProductionRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ReconciliationRoute: typeof ReconciliationRoute
  RoadmapRoute: typeof RoadmapRoute
  TicketsRoute: typeof TicketsRoute
  WellsRoute: typeof WellsRoute
  PartnersPartnerIdRoute: typeof PartnersPartnerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hse': {
      id: '/hse'
      path: '/hse'
      fullPath: '/hse'
      preLoaderRoute: typeof HseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd': {
      id: '/prd'
      path: '/prd'
      fullPath: '/prd'
      preLoaderRoute: typeof PrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wells': {
      id: '/wells'
      path: '/wells'
      fullPath: '/wells'
      preLoaderRoute: typeof WellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$partnerId': {
      id: '/partners/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof PartnersPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ForecastingRoute: ForecastingRoute,
  HseRoute: HseRoute,
  LoginRoute: LoginRoute,
  PrdRoute: PrdRoute,
  ProductionRoute: ProductionRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ReconciliationRoute: ReconciliationRoute,
  RoadmapRoute: RoadmapRoute,
  TicketsRoute: TicketsRoute,
  WellsRoute: WellsRoute,
  PartnersPartnerIdRoute: PartnersPartnerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
