/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventoryRegionRouteImport } from './routes/inventory/$region'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments/index'
import { Route as ShipmentsIdRouteImport } from './routes/shipments/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRegionRoute = InventoryRegionRouteImport.update({
  id: '/inventory/$region',
  path: '/inventory/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIdRoute = ShipmentsIdRouteImport.update({
  id: '/shipments/$id',
  path: '/shipments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/insights': typeof InsightsRoute
  '/production': typeof ProductionRoute
  '/inventory/$region': typeof InventoryRegionRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/insights': typeof InsightsRoute
  '/production': typeof ProductionRoute
  '/inventory/$region': typeof InventoryRegionRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/inventory': typeof InventoryIndexRoute
  '/shipments': typeof ShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/insights': typeof InsightsRoute
  '/production': typeof ProductionRoute
  '/inventory/$region': typeof InventoryRegionRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/insights'
    | '/production'
    | '/inventory/$region'
    | '/shipments/$id'
    | '/inventory/'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/insights'
    | '/production'
    | '/inventory/$region'
    | '/shipments/$id'
    | '/inventory'
    | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/insights'
    | '/production'
    | '/inventory/$region'
    | '/shipments/$id'
    | '/inventory/'
    | '/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  InsightsRoute: typeof InsightsRoute
  ProductionRoute: typeof ProductionRoute
  InventoryRegionRoute: typeof InventoryRegionRoute
  ShipmentsIdRoute: typeof ShipmentsIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$region': {
      id: '/inventory/$region'
      path: '/inventory/$region'
      fullPath: '/inventory/$region'
      preLoaderRoute: typeof InventoryRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/$id': {
      id: '/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof ShipmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  InsightsRoute: InsightsRoute,
  ProductionRoute: ProductionRoute,
  InventoryRegionRoute: InventoryRegionRoute,
  ShipmentsIdRoute: ShipmentsIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
